<?php include 'top.php'; ?>
    <h1><?= $titlePage ?></h1>

    <div class="catalog-card d-flex flex-wrap">

    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis optio delectus eos, sit accusantium, deserunt temporibus eveniet libero hic distinctio tenetur praesentium at, explicabo incidunt rerum necessitatibus quisquam modi? Odio totam tempora tenetur est et vitae repellat voluptatum perferendis voluptates, magni dolorum soluta quos saepe sint architecto, at accusamus nam iusto recusandae. Architecto accusantium dolore earum blanditiis asperiores eius cum non libero sed ad quos quia vitae, beatae adipisci neque in inventore? Temporibus omnis ut at magnam laboriosam perspiciatis esse nam voluptas repellendus. Officiis voluptas doloremque consequatur cupiditate nam quis nobis. Suscipit provident delectus magni cum unde sint, officiis voluptas.</p>
    <p>Voluptatem maxime repudiandae inventore! Dignissimos ducimus quas beatae voluptatum voluptatibus nam hic maiores inventore distinctio saepe quaerat nobis non ipsum numquam quasi reiciendis vero eius eum nulla, laboriosam repudiandae! Totam recusandae neque eius corporis officia, illo architecto a nostrum sapiente. Autem illum debitis eos sapiente quos id perspiciatis placeat, obcaecati quia itaque repellat, at nisi dignissimos harum, facilis molestias architecto laborum! Praesentium sit exercitationem, consequatur inventore necessitatibus molestias quas voluptates nulla nesciunt molestiae fuga in magni, beatae vel reprehenderit reiciendis, laborum architecto quam! Quibusdam exercitationem aliquid reiciendis voluptatem, asperiores iure harum blanditiis, quisquam fugiat voluptatum quia aliquam recusandae corporis expedita?</p>
    <p>Ipsam maxime doloremque, perspiciatis incidunt ad laboriosam sed reiciendis modi soluta facere minus, quia commodi voluptatum cumque tempora non, inventore consequuntur illo quo. Culpa, voluptatibus id. Rerum porro eveniet quidem a ducimus dicta libero quisquam natus autem nulla perferendis soluta quam ipsam eaque, asperiores nesciunt quis illum dolor eius, nihil obcaecati. Explicabo optio nobis illum velit dicta repellendus aperiam, sed, ratione aliquam vero ea vel tempora officia obcaecati totam similique sit nisi distinctio et quod. Odit odio quia soluta expedita dolor quasi officiis blanditiis, ducimus, aliquam unde similique dolorum porro vero reprehenderit praesentium cumque quam ipsum quisquam consequuntur dicta! Ex!</p>
    <p>Ullam non nisi nemo quae. Est quo sint incidunt provident totam soluta quidem minus quis! Ab eos consequatur quas eum similique nulla, ipsum voluptas dolorem obcaecati mollitia! Voluptatibus unde beatae maxime aliquid eos corporis id labore natus velit quia eaque fugit facere nihil nam, debitis harum nesciunt doloribus? Aut excepturi quod ad iste praesentium consectetur voluptates consequatur autem quae rerum molestias at laborum, illum blanditiis. Laboriosam quo suscipit debitis laborum temporibus quasi? Enim nihil veniam ducimus obcaecati, nemo repellendus rerum corporis voluptatibus iusto provident sapiente at non consectetur. Atque esse voluptatum ad quibusdam, doloremque vel accusamus culpa ea molestias tempore.</p>

    </div>

<?php include 'bottom.php'; ?>